project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - Resumen 1-3.qmd
  
website:
  title: "Aprendiendo Computer Science de forma practica!!!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/anthonymorap/ThinkPython-amora
  sidebar:
    style: "docked"
    search: true
    contents:
      - Resumen 1-3.qmd
    page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple

date: today
date-format: iso