project:
  type: website
  render:
    - Resumen 1-3.qmd

website:
  title: "Aprendiendo Computer Science de forma practica!!!"
  site-url: https://anthonymorap.github.io/ThinkPython-amora/
  repo-url: https://github.com/anthonymorap/ThinkPython-amora
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - Resumen 1-3.qmd
    page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple

date: today
date-format: iso