---
title: "Resumen 1-3"
format:
    html:
        toc: true
theme: litera
---


# Capitulo 1: El camino del programa

El autor nos presenta las habilidades de solución de problemas como las más importantes en el mundo del computer science. Ya que esto se traduce en la habilidad de formular problemas, pensar de forma creativa las soluciones, y expresar todo de forma clara y concisa.

Para atacar estos problemas requerimos de **programas** que nos serviran de herramientas para realizar tareas con el computador.

Debajo el cuadro muestra la estructura básica de un programa.

| Elemento              | Descripción                                                                |
|-----------------------|----------------------------------------------------------------------------|
| input                 | origen de los datos como el teclado, un archivo, la red u otro dispositivo |
| output                | se muestra los datos en la pantalla, se graban en otro archivo o se envían |
| math                  | operaciones de matemáticas simples como suma y multiplicación              |
| conditional execution | un chequeo de condiciones para correr el código apropiado                  |
| repetition            | realizar una acción de forma repetida, probablemente con variaciones       |

## Corriendo Python

Para crear estos programas necesitamos un medio a través del cual podamos comunicarnos con el computador. En nuestro caso utilizaremos **Python**, un lenguaje formal sin las ambiguedades de un lenguaje natural como el español, y de alto nivel, por lo que es de fácil comprensión para humanos.

El interprete de Python es un programa que nos permite ejecutar códigos Python.

```{python}
print('hello world!!')
```

Además tenemos acceso a operadores matemáticos, podemos almacenar valores de distintos tipos dentro de variables. Tipos como strings, integers o floating-point numbers.

El uso de un lenguaje formal nos permite obviar los problemas del lenguaje natural como la ambiguedad, redundancia enunciados que no pueden interpretarse de forma literal. Nuestros programas deben ser inambiguos, literales y debemos poder entenderlos completo a través del análisis de tokens y estructura.

**Debugging** es la tarea de los programadores de encontrar bugs y resolverlos para que los programas ejecuten como esperamos.

## Ejercicios

1.1 In a print statement, what happens if you leave out one of the parentheses, or both?


```{{python}}
print('hello world!!'

  Cell In [4], line 1
    print('hello world!!'
                         ^
SyntaxError: incomplete input
```
El interprete entiende que nuestro input esta incompleto, por lo que comprende la función.

```{{python}}
print('hello world!!'

  Cell In [5], line 1
    print'hello world!!'
    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
El interprete entiende que le faltan los paréntesis a la función `print()`.

1.2 If you are trying to print a string, what happens if you leave out one of the quotation marks, or both?

```{{python}}
print(Texto sin quotation marks)

  Cell In [6], line 1
    print(Texto sin quotation marks)
          ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

1.3 You can use a minus sign to make a negative number like -2. What happens if you put a plus sign before a number? What about 2++2?

```{python}
print(+2)
print(2++2)
```

El interprete ignora estos signos de más adicionales.

1.4 In math notation, leading zeros are okay, as in 02. What happens if you try this in Python?

```{{python}}
print(02)

  Cell In [7], line 1
    print(02)
          ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

El interprete indica que leading zeros en integers no esta permitido.

1.5  What happens if you have two values with no operator between them?

```{{python}}
print(2 4)

  Cell In [8], line 1
    print(2 4)
          ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

Sintáxis no válida, pregunta si nos habrémos olvidado de una coma.

2.1 How many seconds are there in 42 minutes 42 seconds?

```{python}
minutes = 42
seconds = 42
minutes_seconds = 42 + (seconds / 60)
total_seconds = (minutes * 60) + seconds
print('En total son {:,} segundos.'.format(total_seconds))
```

2.2 How many miles are there in 10 kilometers? Hint: there are 1.61 kilometers in a mile.

```{python}
km_in_mile = 1.61
total_km = 10
total_miles = round(total_km / km_in_mile, 2)
print('En total serían {:,} millas.'.format(total_miles))
```

2.3 If you run a 10 kilometer race in 42 minutes 42 seconds, what is your average pace (time per mile in minutes and seconds)? What is your average speed in miles per hour?

```{python}
average_pace_seconds = total_seconds / total_miles
average_pace_minutes = average_pace_seconds / 60
average_pace_hour = average_pace_minutes / 60
print('En promedio tomaría {:.2} minutos cada milla, mientras que el promedio por hora es de {:.2} para cada milla.'.format(
  average_pace_minutes, average_pace_hour
))
```


# Capitulo 2: Variables, expresiones y argumentos


Como mencionabamos sobre valores y variables anteriormente, tenemos la oportunidad de realizar assignment statements con los cuales almacenamos valores dentro de variables.




